[package]
name = "iaaa"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7.0"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
